### ISSUE TITLE
[ENHANCEMENT] Add full support for frame labels

### ISSUE THREAD

**Issue by MasterEric** [Dot-Stuff/flxanimate#2]
## Proposal

This enhancement would add the following functions to FlxAnimate:

* `getFrame(label:String):Int` - Returns the frame number corresponding with a given label.
* `goToFrame(label:String):Void` - Sets the current frame of the animation to the frame number corresponding with the given label.
* `getNextLabel(label:String):String` - Returns the name of the next labeled frame, which comes after the label with the provided name.
* `addFrameAction(label:String, callback:Void -> Void):Void` - Defines a callback function which, after the frame with the provided label is reached, will be executed.
* `removeFrameAction(label:String, callback:Void -> Void):Void` - Removes a specific callback function from a given label.
* `removeFrameActions(label:String):Void` - Removes all callback functions from a given label.

## Further Documentation

You can see an example of these features in action here:

* https://wiki.starling-framework.org/extensions/adobe-animate#labels
* https://github.com/Gamua/Starling-Extension-Adobe-Animate/blob/755aacd2628a9417405350f17988c7c7cf63339f/src/starling/extensions/animate/Animation.as

## Example Use Case

Here is an example use case, copied from the link above.

Assume that you have a character sprite, whose Animate atlas definition contains several animations, including walk, run, crouch, and shoot. Without custom logic, the character would walk for a few frames, then run for a few frames, then crouch for a few frames, and shoot for a few frames, which is clearly not the intended behavior.

Instead, we want to perform some action when the individual parts of the animation complete, like so:

```
character.goToFrame('crouch'); // Play the crouch animation.
var nextAnimName = character.getNextLabel('crouch'); // Let's say this returns 'shoot'
character.addFrameAction(nextAnimName, function() {
  // When the animation reaches the frame at the start of the 'shoot' animation,
  // loop back to the beginning of the 'crouch' animation.
  character.goToFrame('crouch');
}
```

The result is that the character can utilize dynamic behavior and animations, without having to rely on swapping between full spritesheets. This saves memory and improves performance.

**Comment by Cheemsandfriends** [comment]
Hm, these are great proposals!
Thanks @MasterEric! I'll write that down to my personal todo list.

**Comment by Cheemsandfriends** [comment]
@MasterEric, Added 3 functions of 6 of the frame labels!
Hope you can test it via git and thank you for the clearing doubts I had while coding the support!

**Comment by Cheemsandfriends** [comment]
@MasterEric, Added support on the frame callbacks shitty thingies, hope you can test it soon!
