### ISSUE TITLE
a FlxAnimateFrames building problem

### ISSUE THREAD

**Issue by Tortu152lol** [Dot-Stuff/flxanimate#24]
flxanimate/frames/FlxAnimateFrames.hx:160: characters 18-20 : Expected )

i dowloaded a mod with this and when i tried to load show's me this error.

**Comment by ACrazyTown** [comment]
Is that mod Hypno V2 by chance? I feel like I've seen that issue there. Even if it is or isn't the main developer of FlxAnimate posted something that should fix it in one of the issues on the repo: https://github.com/PopcornColonell/hypnosource/issues/3#issuecomment-1292134769

**Comment by Tortu152lol** [comment]
so the problem is the brackets right?

**Comment by ACrazyTown** [comment]
> so the problem is the brackets right?

I'm not sure, as I've never had the problem before, but it's worth trying out

**Comment by Tortu152lol** [comment]
so i tried by moving the brackets and still do nothing

**Comment by Tortu152lol** [comment]
i cannot fix it :c

**Comment by Cheemsandfriends** [comment]
Please understand that, altho I myself don't understand how or where tf this is comes from
I cant fix an issue of a private fork that an fnf mod made for whatev the reason.
I appreciate the feedback, but idk what to do with this one tho
![image](https://user-images.githubusercontent.com/84867412/205773269-ebe03dfe-51c5-4b3f-9e46-ce6c3af13496.png)
