### ISSUE TITLE
[BUG]: "Class<flixel.FlxG> has no field mouse" compiler errors

### ISSUE THREAD

**Issue by 8bitjake** [Dot-Stuff/flxanimate#26]
**Describe the bug**
Compiling any project with FlxAnimate in use produces several compiler errors about the same thing.

**Explain how to recreate the bug**
For example: Steps to reproduce the behavior:
1. Use FlxAnimate v3.0.3 in any project
2. Compile
3. These errors appear: 
![image](https://user-images.githubusercontent.com/75950907/213566823-ce608936-6bd7-4ba1-9903-fbd0777009cd.png)

**What should happen?**
I'm assuming animations should play correctly, if at all. I don't know for sure what _should_ happen though, since this was in a testing project I made to get the hang of using FlxAnimate.

**Adobe Animate Version**
Adobe Animate version v23.0

**Comment by ACrazyTown** [comment]
Seems like for some reason your Flixel project isn't giving you access to the mouse property, this only happens if you have the `FLX_MOUSE` define disabled. Do you have the `FLX_NO_MOUSE` define declared by chance?

**Comment by 8bitjake** [comment]
Removing the `FLX_NO_MOUSE` define seemed to fix the problem. Thanks!
