### ISSUE TITLE
Adding animations and setting the frame length not supported in 2019 or 2018 mostly

### ISSUE THREAD

**Issue by ACrazyTown** [Dot-Stuff/flxanimate#3]
idk why, but like when I try to compile a simple test project on HTML5 (and Windows I believe!) I get an issue about timeline being undefined,
these are the lines of code i used:
`var sus = new FlxAnimate(0, 0, "assets/images/cool", {FrameRate: 24});
		sus.playAnim("Ding cool anim");
		add(sus);
`
and this is the error I got:
![image](https://user-images.githubusercontent.com/47027981/158645071-2eef51ac-5e32-4a2a-9f9e-0307ca44cc7c.png)

**Comment by Cheemsandfriends** [comment]
I should really explain what does `playAnim` do, but basically @ACrazyTown, The name are the animations that you added, for ex: if you called `sus.anim.addBySymbol("Sussus", "amogus", 24);` You can call the animation that you call with `sus.playAnim("Sussus");` but if you want to play the main animation, you should call `sus.playAnim();`!

But this is a reminder there's a vulnerability on playAnim, Thanks!

**Comment by Cheemsandfriends** [comment]
Hm...
Weird, is there a way that you could pass the code which you call the stuff and the texture atlas itself? 
if you don't mind oc

**Comment by ACrazyTown** [comment]
> Hm... Weird, is there a way that you could pass the code which you call the stuff and the texture atlas itself? if you don't mind oc It could be perfectly possible that something's unsupported and I don't know

I figured it out by using another spritesheet and it worked fine, so that makes me believe that the FlxAnimate parser can't parse shape tweens in the `Animation.json` file rn (the old spritesheet I used had shape tweens)?

Either way I got it working, sorry for wasting a bit of your time lol!

**Comment by Cheemsandfriends** [comment]
> > Hm... Weird, is there a way that you could pass the code which you call the stuff and the texture atlas itself? if you don't mind oc It could be perfectly possible that something's unsupported and I don't know
> 
> I figured it out by using another spritesheet and it worked fine, so that makes me believe that the FlxAnimate parser can't parse shape tweens in the `Animation.json` file rn (the old spritesheet I used had shape tweens)?
> 
> Either way I got it working, sorry for wasting a bit of your time lol!

Wait what??
This is interesting, shape tween stuff has all the thing exported and blablabla, Could I see the old texture atlas?

**Comment by Cheemsandfriends** [comment]
Ah, I see the problem right now, Srry for the inconvenience, rn we use 2021 as the model for the Animation.json, Should open this issue but I'm gonna rename the issue to something else

**Comment by Cheemsandfriends** [comment]
From what I was looking into, I think it's already fixed!
Thank you @ACrazyTown for informing of the issue and sorry for the inconvenience!
