### ISSUE TITLE
[BUG] FPS Drop when FlxAnimate is removed

### ISSUE THREAD

**Issue by DotWith** [Dot-Stuff/flxanimate#4]
FPS Drops when FlxAnimate is destroyed. Perhaps it's the children still being rendered and not destroyed properly. I was able to fix this in my project so far by using onComplete to remove.

**Comment by Cheemsandfriends** [comment]
using the destroy function right?
Yeah, there should be an overriding of the destroy making those stuff idk

**Comment by Cheemsandfriends** [comment]
Not fixed yet, but it should be basically simple, just overriding destroy iirc

**Comment by Cheemsandfriends** [comment]
Removed the issue, I think?
