### ISSUE TITLE
[HELP] I just don't really know how to export texture atlases

### ISSUE THREAD

**Issue by Chidubemmo** [Dot-Stuff/flxanimate#44]
I'm sorry if it sounds obvious for you guys but I don't know how to export every animation in a single spritemap. If I try to select multiple symbols, there isn't the option.
I need to figure out how to do it so I can put it in my game

**Comment by Cheemsandfriends** [comment]
I'll do an extensive FQ so it's nice and tidy, but to put in simple terms:

Texture atlases dont have the capacity to support separate symbols on its own, a fix to this is to include in a temporary symbol every symbol that you need with the organisation you want and then you hit export

**Comment by Chidubemmo** [comment]
ok
