### ISSUE TITLE
[BUG] Error happend when flixel.input.mouse.FlxMouse

### ISSUE THREAD

**Issue by TheKitBoi** [Dot-Stuff/flxanimate#6]
Error: C:/haxelib/flxAnimate/1,0,1/flxanimate/FlxAnimate.hx:181: characters 20-28 : flixel.input.mouse.FlxMouse has no field released #

**Comment by Cheemsandfriends** [comment]
Oh, Yeah, I forgot, I'm using a very heavily modified version of flixel, so it'll have some current flixel development thingies and not, I'm very sorry!
Gonna fix it with the traditional commits I'm gonna do!

**Comment by Cheemsandfriends** [comment]
@TheKitBoi, The issue is fixed and the button support is even more enhanced and similar to Adobe Animate!
Srry for the inconvenience! lol
