### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by TheKitBoi** [Dot-Stuff/flxanimate#9]
**Describe the bug**
Explain the bug as clear as possible, no code involving.

The Sample crashes on startup from the git version

**Adobe Animate Version**
Adobe Animate version [2022].

**Additional context**

**Comment by Cheemsandfriends** [comment]
Uhm
Can you elaborate more about it?
Could you add the crash error pls?
Could you also add the texture atlas that gives you the crash to test it properly?

this issue doesn't give me much info lol

**Comment by TheKitBoi** [comment]
may bring it back once i get the error message
